@startuml TableUML

skinparam BackgroundColor ghostwhite

package table{
    class PickablesTable{
        -commonObjectives : Arraylist<ObjectiveCard>
        -shownCards: Arraylist<PlayableCard>
        -NumOfObjectives : int
        -NumOfShownPerType : int

        +getShownCards(): Arraylist<PlayableCard>
        +getCommonObjectives(): Arraylist<ObjectiveCard>

        +putCard(PlayableCard): void
        +putObjective(ObjectiveCard): void
        +pickCard(int): PlayableCard
        '+clearALL(): void
        +pickAll(Map<DeckType, Deck>): void 
    }

    class Plateau{
        -playerPoints: Map<Player, Integer>
        -armageddonTime : int
        -numOfPlayers : int
        -isArmageddonTime : boolean

        +reset(): void
        +addPlayer(Player): void
        +addPlayerPoints(Player, int): void
        +getPlayerPoints(Player): int
        +getLeadingPlayer(): List<Player>
    }
}

@enduml